name: Publish to Nuget
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
          
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.0
      with:
        dotnet-version: 3.1.201
      
    - name: Install dependencies
      run: dotnet restore
    
    - name: Set version in project file
      uses: roryprimrose/set-vs-sdk-project-version@v1.0.3
      with:
        version: 1.${{ github.run_number }}.0

    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: ./src/Fable.ReactBeautifulDnD.fsproj
        VERSION_STATIC: 1.${{ github.run_number }}.0
        TAG_COMMIT: true
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        INCLUDE_SYMBOLS: false
